# Boston Earnings
This notebook builds off Boston Pensions Pt 1. Instead of just looking at cop pay in this data, I will use it to find cop pay as % of total pay for the pension analysis and hopefully ultimately for our final calculation of what the Boston PD costs. 

This dataset has in it total payments to boston cops over 2016-2020 that's great than the total stated budget of the Boston PD. There are no columns for "pension" in this data, so current assumption is that discrepancy is due to what we vera called "fringe" benefits in https://www.vera.org/downloads/publications/a-look-inside-the-new-york-city-police-department-budget.pdf

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.3f' % x)
# from Boston_Earnings_Helpers import get_numeric, string_to_float

In [3]:
to_float_cols = ["REGULAR", "RETRO", "OTHER", "OVERTIME", 
                 "INJURED", "DETAIL","QUINN/EDUCATION INCENTIVE", "TOTAL EARNINGS"]

First thing to check is if we got all the data

In [4]:
boston_earnings_2019 = pd.read_csv("../data/BostonPD/Boston_Earnings_2019.csv")

In [71]:
def string_to_float(val):
    if isinstance(val, int) or isinstance(val, float):
        return val
    elif "-" in val:
        return 0
    else:
        return to_numeric(val)

def to_numeric(val):
    for c in [" ", ",", "(", ")"]:
        val = val.replace(c, "")
    try:
        return float(val)
    except:
        return 0

In [72]:
boston_earnings_2019.head(5)

,NAME,DEPARTMENT_NAME,TITLE,REGULAR,RETRO,OTHER,OVERTIME,INJURED,DETAIL,QUINN/EDUCATION INCENTIVE,TOTAL EARNINGS,POSTAL,year
0,"Abadi,Kidani A",Assessing Department,Property Utilization Officer,70738.870,0.000,275.000,0.000,0.000,0.000,0.000,71013.870,2118,2019
1,"Abajue Umeh,Kenechukwu Stephanie",BPS Boston Arts Academy,Teacher,67296.000,1290.630,500.000,0.000,0.000,0.000,0.000,69086.630,2150,2019
2,"Abasciano,Joseph",Boston Police Department,Police Officer,94156.490,0.000,850.000,26496.590,0.000,5980.000,23539.210,151022.290,2132,2019
3,"Abatzis,Kelley",BPS Health and Wellness,Employment Agreement,5880.000,0.000,0.000,0.000,0.000,0.000,0.000,5880.000,2171,2019
4,"Abban,Christopher John",Boston Fire Department,Fire Fighter,118315.560,8766.010,3680.980,18437.270,2279.780,1944.000,0.000,153423.600,2132,2019

In [73]:
boston_earnings_2019[to_float_cols] = boston_earnings_2019[to_float_cols].applymap(string_to_float)
boston_earnings_2019["year"] = 2019

In [74]:
boston_earnings_2019["INJURED"].sum()

39958682.77

In [75]:
boston_earnings = boston_earnings_2019
for year in (2018, 2017, 2016):
    print("got to year", year)
    earnings = pd.read_csv("../data/BostonPD/Boston_Earnings_" + str(year) + ".csv", engine="python")
    earnings["year"] = year
    if year == 2017:
        earnings.rename(columns = {"DEPARTMENT NAME":"DEPARTMENT_NAME"}, inplace=True)
    earnings[to_float_cols] = earnings[to_float_cols].applymap(string_to_float)
    boston_earnings = boston_earnings.append(earnings)
boston_earnings.shape

got to year 2018
got to year 2017
got to year 2016

(91208, 13)

In [79]:
boston_earnings.groupby("year").sum()

,REGULAR,RETRO,OTHER,OVERTIME,INJURED,DETAIL,QUINN/EDUCATION INCENTIVE,TOTAL EARNINGS
year,,,,,,,,
2016,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2017,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2018,1416825526.630,29946840.600,52691623.900,120139913.710,33104131.130,42936237.430,24947885.890,1720567517.370
2019,1470657000.870,34122856.390,55433468.960,127017515.860,39958682.770,40698940.490,28871146.820,1796738085.860

Empty DataFrame
Columns: [NAME, DEPARTMENT_NAME, TITLE, REGULAR, RETRO, OTHER, OVERTIME, INJURED, DETAIL, QUINN/EDUCATION INCENTIVE, TOTAL EARNINGS, POSTAL]
Index: []

In [37]:
boston_earnings.groupby("year").size()

year
2016    22046
2017    22245
2018    23605
2019    23312
dtype: int64

In [38]:
pd.set_option("display.max.rows", 50)
boston_earnings.groupby("DEPARTMENT_NAME").sum()[to_float_cols].sort_values("TOTAL EARNINGS", ascending=False).head(50)

,REGULAR,RETRO,OTHER,OVERTIME,INJURED,DETAIL,QUINN/EDUCATION INCENTIVE,TOTAL EARNINGS
DEPARTMENT_NAME,,,,,,,,
Boston Police Department,939454359.950,37678617.690,59306315.890,283560824.630,55878351.840,143621695.000,92865300.880,1612273457.620
Boston Fire Department,690720960.060,17635020.570,28619090.430,100547361.420,43860829.400,30719115.860,13084.310,912059861.490
BPS Special Education,180868335.850,2169903.360,3863371.720,86694.920,92770.960,0.000,0.000,187081076.810
BPS Facility Management,97960341.080,1275581.430,2855488.920,8006991.630,1143738.940,0.000,0.000,111241707.200
Boston Public Library,103189114.150,1757227.990,2121524.780,2737974.750,100169.260,0.000,0.000,109906010.930
Public Works Department,83572033.550,377135.530,1640633.400,19038651.110,1330686.820,0.000,0.000,105959140.410
Boston Cntr - Youth & Families,87047918.880,540181.180,1410248.990,1190382.790,40860.130,0.000,0.000,90229591.970
Traffic Division,74010454.400,291004.140,1396474.880,6792476.720,1291974.570,0.000,0.000,83782384.710
Inspectional Services Dept,58817112.210,328189.930,2063774.520,6321548.990,146396.280,1148.000,0.000,67676174.850
BPS Boston Latin,61170760.180,678574.120,1815095.240,145.890,0.000,0.000,0.000,63664575.430
Parks Department,53433782.130,265053.520,709239.090,6626865.480,200059.500,346701.900,0.000,61581701.620
BPS Human Resource Team,53610429.000,553231.510,5784656.470,453994.520,147938.710,0.000,0.000,60550250.210
BPS Madison Park High,56392525.870,616350.040,2392589.570,14469.940,5165.460,0.000,0.000,59421100.880
BPS Substitute Teachers/Nurs,56106780.330,653886.690,2069710.860,4614.520,122580.370,0.000,0.000,58957572.770
BPS McKinley Middle,53401106.260,586024.270,1443617.440,625.560,31900.110,0.000,0.000,55463273.640
Dpt of Innovation & Technology,51223996.900,332717.160,1226473.620,1606782.210,108777.170,0.000,0.000,54498747.060
BPS East Boston High,49211093.620,535595.000,2012312.580,34168.720,0.000,0.000,0.000,51793169.920
BPS Latin Academy,45260130.790,503379.090,1120804.070,886.430,48090.840,0.000,0.000,46933291.220
BPS Transportation,43278288.270,738476.710,852660.930,112758.260,170706.540,0.000,0.000,45152890.710
Neighborhood Development,42871531.330,242945.780,966301.120,6241.970,13758.490,0.000,0.000,44100778.690
Curley K-8,41923327.990,503179.630,1524822.490,14740.120,32437.370,0.000,0.000,43998507.600
BPS O'Bryant School,41145551.520,478163.760,1583673.300,0.000,10471.150,0.000,0.000,43217859.730
Property Management,30992874.360,401322.160,998408.570,7751606.190,188063.900,2429159.150,0.000,42761434.330
Tech Boston Academy,40117771.760,418038.910,1113989.860,1451.930,26328.010,0.000,0.000,41677580.470
Henderson Elementary,38983595.060,450619.270,1030393.420,4820.190,215.390,0.000,0.000,40469643.330
BPS Charlestown High,37983950.630,411595.610,1897431.480,1655.610,25688.660,0.000,0.000,40317880.490
BPS Murphy Elementary,37298427.380,450600.180,816812.740,15112.120,10454.350,0.000,0.000,38591406.770
BPS Condon Elementary,36496542.050,430133.210,780801.300,1079.480,197859.920,0.000,0.000,37906415.960
BPS Lee Elementary,35781895.590,391264.780,953451.040,1365.580,36023.400,0.000,0.000,37164000.390
BPS Orchard Gardens K-8 Pilot,35501311.520,414221.100,900951.760,15282.080,0.000,0.000,0.000,36831766.460
BPS Quincy Elementary,33292915.270,400940.390,1393368.370,0.000,35041.800,0.000,0.000,35122265.830
Umana Middle,33599864.510,375631.310,978712.030,1429.110,4611.450,0.000,0.000,34960248.410
Jackson/Mann K-8,31461799.740,347286.940,1402708.770,3594.950,390888.940,0.000,0.000,33606279.340
Edison K-8,29759212.940,353561.630,991051.160,5134.110,13174.610,0.000,0.000,31122134.450
BPS Brighton High,28968314.490,282745.010,1803347.980,250.380,9700.960,0.000,0.000,31064358.820
BPS English High,27282474.270,287665.740,1378539.870,348.160,95116.290,0.000,0.000,29044144.330
BPS Counseling Service,27581264.100,325644.140,682161.240,0.000,39465.120,0.000,0.000,28628534.600
BPS Horace Mann,26527322.080,323766.600,1081162.990,0.000,8410.600,0.000,0.000,27940662.270
BPS Blackstone Elementary,26046700.670,294633.930,708754.280,2013.760,24380.310,0.000,0.000,27076482.950
BPS Hennigan Elementary,25747593.620,293412.560,860179.840,16838.460,10424.430,0.000,0.000,26928448.910
BPS Mckay Elementary,25637357.400,323344.450,689768.740,7319.210,1252.880,0.000,0.000,26659042.680
BPS Ohrenberger Elementary,24981440.930,287551.060,566182.790,15.910,4337.540,0.000,0.000,25839528.230
Assessing Department,24544532.260,135955.040,612307.080,103878.010,36486.060,0.000,0.000,25433158.450
Young Achievers K-8,24113795.970,247420.780,713170.860,3379.000,8152.580,0.000,0.000,25085919.190
UP Academy Holland,24267960.130,69006.220,311519.960,379611.140,0.000,0.000,0.000,25028097.450
UP Academy Dorchester,23890737.550,221686.540,258834.950,134056.650,0.000,0.000,0.000,24505315.690
BPS Mather Elementary,23271968.520,267394.390,814363.650,1825.520,3043.480,0.000,0.000,24358595.560
Mildred Avenue K-8,22896966.790,264838.290,981240.560,5942.600,54944.930,0.000,0.000,24203933.170
Warren/Prescott K-8,22911637.810,269862.100,736072.760,0.000,0.000,0.000,0.000,23917572.670
BPS Sumner Elementary,22633937.240,264763.940,938502.840,1758.180,5307.640,0.000,0.000,23844269.840

In [39]:
bostonPD_by_year = boston_earnings[boston_earnings["DEPARTMENT_NAME"]=="Boston Police Department"]\
                    .groupby("year").sum()["TOTAL EARNINGS"]
total_by_year = boston_earnings.groupby("year").sum()["TOTAL EARNINGS"]
total_by_year

year
2016   1580210286.370
2017   1590905618.100
2018   1720567517.370
2019   1796738085.860
Name: TOTAL EARNINGS, dtype: float64

In [40]:
bostonPD_by_year/total_by_year

year
2016   0.246
2017   0.246
2018   0.242
2019   0.231
Name: TOTAL EARNINGS, dtype: float64

In [42]:
bostonPD_by_year

year
2016   388587231.110
2017   391277619.770
2018   416682999.940
2019   415725606.800
Name: TOTAL EARNINGS, dtype: float64

In [80]:
import sys
import os
sys.path.insert(0, "/pensions")
from LocalPD_True_Payroll import Boston_total_earnings

In [86]:
boston_total_no_teachers, boston_total = Boston_total_earnings()

WARNING! IN DEBUG MODE

In [85]:
boston_total.loc[boston_total["department"] == "Boston Police Department", "TOTAL EARNINGS"].sum()/\
boston_total.loc[:,"TOTAL EARNINGS"].sum()

0.24105440360836722

In [88]:
boston_total_no_teachers.loc[boston_total_no_teachers["department"] == "Boston Police Department", "TOTAL EARNINGS"].sum()/\
boston_total_no_teachers.loc[:,"TOTAL EARNINGS"].sum()

0.4289951144834596