Created this notebook to find supreme judicial court, appeals court pensions

In [5]:
import pandas as pd
import os
import sys
sys.path.insert(0, os.path.abspath("../"))
import Statewide_Pensions
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [8]:
by_agency = Statewide_Pensions.pensions_by_agency(False)

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/series.py:4536: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/Users/alexanderweinstein/Documents/Harris/Summer2020/Carceral_Budgeting/Exploratory/Cost_Type_Code/Pensions/Statewide_Pensions.py:144: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthru_pensions["year"] = cthru_pensions["year"].astype(int)

In [9]:
by_agency.index

In [11]:
pensions = Statewide_Pensions.get_cthru_pension_payouts(False)

In [12]:
pensions.head(5)

,Unnamed: 0,trans_no,last_name,first_name,date_of_retirement,title_at_retirement,department,monthly_amount,year,position_type,retirement_system,annual_amount,agency_class
0,0,S00000689,Beaudreault,Gerald,2015-08-03T00:00:00.000,None,Univ. Of Mass Medical School,8938.230,2015,Full,MSERS,107258.760,None
1,1,S00001183,Hayes,Catherine,1992-07-01T00:00:00.000,None,"Budget Bureau, Central Bus.off",3164.180,2015,Full,MSERS,37970.160,None
2,2,S00001222,Higgins,John,2002-03-15T00:00:00.000,Fiscal Officer Viii,"Budget Bureau, Central Bus.off",3846.300,2015,Full,MSERS,46155.600,None
3,3,S00001339,"Lee, Jr.",Thomas,2015-06-30T00:00:00.000,Fiscal Officer vi,Commission For The Blind,5226.480,2015,Full,MSERS,62717.760,None
4,4,S00001391,Mahoney,Paul,2008-08-15T00:00:00.000,First Justice,Senate Rules Committee,2933.650,2015,Full,MSERS,35203.800,None

In [18]:
pd.set_option("display.max.rows", 642)
pensions[pensions["department"].str.contains("(?i)youth")].groupby("department").sum()["annual_amount"].sort_values(ascending=False)

department
Children, Youth And Families    123873736.080
Human Services,children,youth    88803762.960
Children Youth & Families        57971533.440
Youth Service Treatment            425060.520
Jj Connolly Youth Ctr.              61353.120
Name: annual_amount, dtype: float64

In [15]:
pensions[pensions['department'].str.contains("(?i)youth")]

,Unnamed: 0,trans_no,last_name,first_name,date_of_retirement,title_at_retirement,department,monthly_amount,year,position_type,retirement_system,annual_amount,agency_class
229,229,S00016640,Boden,Peter,2013-10-18T00:00:00.000,Edp Systems Analyst ii,"Human Services,children,youth",4509.040,2015,Full,MSERS,54108.480,None
239,239,S00020189,White,Dorothy,2014-12-05T00:00:00.000,Program Coordinator ii,"Human Services,children,youth",4655.130,2015,Full,MSERS,55861.560,None
440,440,S00048438,Coburn,Sally,2013-11-08T00:00:00.000,Auditor iv,"Children, Youth And Families",3669.990,2015,Full,MSERS,44039.880,None
844,844,S00090025,Schram,Ivy,2002-03-15T00:00:00.000,Administrator Vii,Children Youth & Families,2587.910,2015,Full,MSERS,31054.920,None
894,894,S00083551,Ko,Wendy,2015-06-30T00:00:00.000,Administrative Officer V,"Children, Youth And Families",4533.540,2015,Full,MSERS,54402.480,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
737542,737542,S02513628,Thompson,Mary,2012-08-10T00:00:00.000,Personnel Officer I,"Human Services,children,youth",4088.820,2020,Full,MSERS,49065.840,None
737579,737579,S00334334,Kaufman,Stuart,1999-07-17T00:00:00.000,None,"Human Services,children,youth",2948.360,2020,Full,MSERS,35380.320,None
737750,737750,S03005444,Mckinnon,Ruth,2006-08-10T00:00:00.000,Program Manager V,"Children, Youth And Families",2104.910,2020,Full,MSERS,25258.920,None
737822,737822,S00455455,Petricone,Marie,2002-03-15T00:00:00.000,Program Coordinator Iii,"Children, Youth And Families",3912.540,2020,Full,MSERS,46950.480,None
737858,737858,S00444444,Fitzgerald,Frances,1993-12-31T00:00:00.000,None,"Children, Youth And Families",1324.890,2020,Full,MSERS,15898.680,None

Not clear where dept of youth services pensions are. I'm wary to use pensions from departments that mention families. This leaves "Youth Service Treatment" which is far too small but the best thing to use